-- liquibase formatted sql

--changeset Dm:1

CREATE TABLE advertisement
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email   VARCHAR(255),
    image   VARCHAR(255),
    price   INTEGER,
    title   VARCHAR(255),
    user_id BIGINT,
    CONSTRAINT pk_advertisement PRIMARY KEY (id)
);

CREATE TABLE comments
(
    comment_id        BIGINT NOT NULL,
    author_image      VARCHAR(255),
    author_first_name VARCHAR(255),
    created_at        INTEGER,
    text              VARCHAR(255),
    author_id         BIGINT,
    ad_entity_id      BIGINT,
    CONSTRAINT pk_comments PRIMARY KEY (comment_id)
);

CREATE TABLE image
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_path  VARCHAR(255),
    file_size  BIGINT                                  NOT NULL,
    media_type VARCHAR(255),
    data       OID,
    ad_id      BIGINT,
    CONSTRAINT pk_imageentity PRIMARY KEY (id)
);

CREATE TABLE users
(
    user_id    BIGINT NOT NULL,
    email      VARCHAR(255),
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    phone      VARCHAR(255),
    role       VARCHAR(255),
    password   VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

ALTER TABLE image
    ADD CONSTRAINT uc_imageentity_ad UNIQUE (ad_id);

ALTER TABLE advertisement
    ADD CONSTRAINT FK_ADVERTISEMENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_ADENTITYID FOREIGN KEY (ad_entity_id) REFERENCES advertisement (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (user_id);

ALTER TABLE image
    ADD CONSTRAINT FK_IMAGEENTITY_ON_AD FOREIGN KEY (ad_id) REFERENCES advertisement (id);

--changeset Dm:2
CREATE SEQUENCE IF NOT EXISTS users_seq START WITH 1 INCREMENT BY 50;


--changeset Dm:3
ALTER TABLE advertisement ADD COLUMN image_id BIGINT;
ALTER TABLE advertisement ADD CONSTRAINT fk_advertisement_image
    FOREIGN KEY (image_id) REFERENCES image(id);
